/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreCopaRouteImport } from './routes/sobre-copa'
import { Route as PalpitarRouteImport } from './routes/palpitar'
import { Route as MeusPalpitesRouteImport } from './routes/meus-palpites'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const SobreCopaRoute = SobreCopaRouteImport.update({
  id: '/sobre-copa',
  path: '/sobre-copa',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitarRoute = PalpitarRouteImport.update({
  id: '/palpitar',
  path: '/palpitar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPalpitesRoute = MeusPalpitesRouteImport.update({
  id: '/meus-palpites',
  path: '/meus-palpites',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/palpitar': typeof PalpitarRoute
  '/sobre-copa': typeof SobreCopaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/palpitar': typeof PalpitarRoute
  '/sobre-copa': typeof SobreCopaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/palpitar': typeof PalpitarRoute
  '/sobre-copa': typeof SobreCopaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/meus-palpites' | '/palpitar' | '/sobre-copa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/meus-palpites' | '/palpitar' | '/sobre-copa'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/meus-palpites'
    | '/palpitar'
    | '/sobre-copa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  MeusPalpitesRoute: typeof MeusPalpitesRoute
  PalpitarRoute: typeof PalpitarRoute
  SobreCopaRoute: typeof SobreCopaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-copa': {
      id: '/sobre-copa'
      path: '/sobre-copa'
      fullPath: '/sobre-copa'
      preLoaderRoute: typeof SobreCopaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpitar': {
      id: '/palpitar'
      path: '/palpitar'
      fullPath: '/palpitar'
      preLoaderRoute: typeof PalpitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-palpites': {
      id: '/meus-palpites'
      path: '/meus-palpites'
      fullPath: '/meus-palpites'
      preLoaderRoute: typeof MeusPalpitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  MeusPalpitesRoute: MeusPalpitesRoute,
  PalpitarRoute: PalpitarRoute,
  SobreCopaRoute: SobreCopaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
