/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreCopaRouteImport } from './routes/sobre-copa'
import { Route as MeusPalpitesRouteImport } from './routes/meus-palpites'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PalpitarIndexRouteImport } from './routes/palpitar.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PalpitarJogoIdRouteImport } from './routes/palpitar.$jogoId'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSorteiosRouteImport } from './routes/admin.sorteios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJogosRouteImport } from './routes/admin.jogos'
import { Route as AdminJogoIdRouteImport } from './routes/admin.jogo.$id'

const SobreCopaRoute = SobreCopaRouteImport.update({
  id: '/sobre-copa',
  path: '/sobre-copa',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPalpitesRoute = MeusPalpitesRouteImport.update({
  id: '/meus-palpites',
  path: '/meus-palpites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitarIndexRoute = PalpitarIndexRouteImport.update({
  id: '/palpitar/',
  path: '/palpitar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitarJogoIdRoute = PalpitarJogoIdRouteImport.update({
  id: '/palpitar/$jogoId',
  path: '/palpitar/$jogoId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSorteiosRoute = AdminSorteiosRouteImport.update({
  id: '/admin/sorteios',
  path: '/admin/sorteios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogosRoute = AdminJogosRouteImport.update({
  id: '/admin/jogos',
  path: '/admin/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogoIdRoute = AdminJogoIdRouteImport.update({
  id: '/admin/jogo/$id',
  path: '/admin/jogo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/sobre-copa': typeof SobreCopaRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/palpitar/$jogoId': typeof PalpitarJogoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/palpitar/': typeof PalpitarIndexRoute
  '/admin/jogo/$id': typeof AdminJogoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/sobre-copa': typeof SobreCopaRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/palpitar/$jogoId': typeof PalpitarJogoIdRoute
  '/admin': typeof AdminIndexRoute
  '/palpitar': typeof PalpitarIndexRoute
  '/admin/jogo/$id': typeof AdminJogoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/meus-palpites': typeof MeusPalpitesRoute
  '/sobre-copa': typeof SobreCopaRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/sorteios': typeof AdminSorteiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/palpitar/$jogoId': typeof PalpitarJogoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/palpitar/': typeof PalpitarIndexRoute
  '/admin/jogo/$id': typeof AdminJogoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/confirmacao'
    | '/meus-palpites'
    | '/sobre-copa'
    | '/admin/jogos'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/sorteios'
    | '/admin/usuarios'
    | '/palpitar/$jogoId'
    | '/admin/'
    | '/palpitar/'
    | '/admin/jogo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/confirmacao'
    | '/meus-palpites'
    | '/sobre-copa'
    | '/admin/jogos'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/sorteios'
    | '/admin/usuarios'
    | '/palpitar/$jogoId'
    | '/admin'
    | '/palpitar'
    | '/admin/jogo/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/confirmacao'
    | '/meus-palpites'
    | '/sobre-copa'
    | '/admin/jogos'
    | '/admin/login'
    | '/admin/produtos'
    | '/admin/sorteios'
    | '/admin/usuarios'
    | '/palpitar/$jogoId'
    | '/admin/'
    | '/palpitar/'
    | '/admin/jogo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  MeusPalpitesRoute: typeof MeusPalpitesRoute
  SobreCopaRoute: typeof SobreCopaRoute
  AdminJogosRoute: typeof AdminJogosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminSorteiosRoute: typeof AdminSorteiosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  PalpitarJogoIdRoute: typeof PalpitarJogoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PalpitarIndexRoute: typeof PalpitarIndexRoute
  AdminJogoIdRoute: typeof AdminJogoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-copa': {
      id: '/sobre-copa'
      path: '/sobre-copa'
      fullPath: '/sobre-copa'
      preLoaderRoute: typeof SobreCopaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-palpites': {
      id: '/meus-palpites'
      path: '/meus-palpites'
      fullPath: '/meus-palpites'
      preLoaderRoute: typeof MeusPalpitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpitar/': {
      id: '/palpitar/'
      path: '/palpitar'
      fullPath: '/palpitar/'
      preLoaderRoute: typeof PalpitarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpitar/$jogoId': {
      id: '/palpitar/$jogoId'
      path: '/palpitar/$jogoId'
      fullPath: '/palpitar/$jogoId'
      preLoaderRoute: typeof PalpitarJogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sorteios': {
      id: '/admin/sorteios'
      path: '/admin/sorteios'
      fullPath: '/admin/sorteios'
      preLoaderRoute: typeof AdminSorteiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogos': {
      id: '/admin/jogos'
      path: '/admin/jogos'
      fullPath: '/admin/jogos'
      preLoaderRoute: typeof AdminJogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogo/$id': {
      id: '/admin/jogo/$id'
      path: '/admin/jogo/$id'
      fullPath: '/admin/jogo/$id'
      preLoaderRoute: typeof AdminJogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  MeusPalpitesRoute: MeusPalpitesRoute,
  SobreCopaRoute: SobreCopaRoute,
  AdminJogosRoute: AdminJogosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminSorteiosRoute: AdminSorteiosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  PalpitarJogoIdRoute: PalpitarJogoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  PalpitarIndexRoute: PalpitarIndexRoute,
  AdminJogoIdRoute: AdminJogoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
